# Generated by Django 4.2.28 on 2026-02-17 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import music.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='For tracking anonymous users', max_length=100, verbose_name='session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'ad click',
                'verbose_name_plural': 'ad clicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='For tracking anonymous users', max_length=100, verbose_name='session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'ad impression',
                'verbose_name_plural': 'ad impressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ad_type', models.CharField(choices=[('BANNER', 'Banner'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('INTERSTITIAL', 'Interstitial')], default='BANNER', max_length=20, verbose_name='ad type')),
                ('placement', models.CharField(choices=[('HOME_TOP', 'Home Top'), ('HOME_MIDDLE', 'Home Middle'), ('PLAYER', 'Player'), ('SEARCH', 'Search'), ('PLAYLIST', 'Playlist')], default='HOME_TOP', max_length=20, verbose_name='placement')),
                ('image', models.ImageField(blank=True, help_text='For banner and interstitial ads', null=True, upload_to='ads/images/', verbose_name='image')),
                ('video_file', models.FileField(blank=True, help_text='For video ads', null=True, upload_to='ads/videos/', verbose_name='video file')),
                ('audio_file', models.FileField(blank=True, help_text='For audio ads', null=True, upload_to='ads/audio/', verbose_name='audio file')),
                ('click_url', models.URLField(help_text='URL to redirect when ad is clicked', max_length=500, verbose_name='click URL')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds (for video/audio ads)', verbose_name='duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority ads are shown first', verbose_name='priority')),
                ('impression_count', models.PositiveIntegerField(default=0, verbose_name='impression count')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='click count')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'advertisement',
                'verbose_name_plural': 'advertisements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/', validators=[music.validators.validate_image_file_size], verbose_name='cover image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('bio_ar', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/', validators=[music.validators.validate_image_file_size], verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('audio_file', models.FileField(upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'aac', 'm4a']), music.validators.validate_audio_file_size], verbose_name='audio file')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds', verbose_name='duration')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('ARABIC', 'Arabic'), ('INSTRUMENTAL', 'Instrumental'), ('BILINGUAL', 'Bilingual')], default='ENGLISH', max_length=20, verbose_name='language')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='play count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.album', verbose_name='album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='music.artist', verbose_name='artist')),
            ],
            options={
                'verbose_name': 'music',
                'verbose_name_plural': 'music',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=50, null=True, unique=True, verbose_name='name')),
                ('category', models.CharField(choices=[('MOOD', 'Mood'), ('GENRE', 'Genre'), ('THEME', 'Theme')], default='MOOD', max_length=20, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('color_code', models.CharField(default='#000000', help_text='Hex color code for UI display', max_length=7, verbose_name='color code')),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='music_tag_categor_ae50ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='played at')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_plays', to='music.music', verbose_name='music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'recently played',
                'verbose_name_plural': 'recently played',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('music_tracks', models.ManyToManyField(blank=True, related_name='playlists', to='music.music', verbose_name='music tracks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='music_tracks', to='music.tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='music',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_music', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.music', verbose_name='music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='music_artis_name_e97718_idx'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist', verbose_name='artist'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['placement', 'is_active', '-priority'], name='music_adver_placeme_afa67e_idx'),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='music.advertisement', verbose_name='advertisement'),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='adclick',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='music.advertisement', verbose_name='advertisement'),
        ),
        migrations.AddField(
            model_name='adclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='recentlyplayed',
            index=models.Index(fields=['user', '-played_at'], name='music_recen_user_id_3cb9a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyplayed',
            unique_together={('user', 'music')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', '-updated_at'], name='music_playl_user_id_ab4a82_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['artist', '-created_at'], name='music_music_artist__f29e89_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['album'], name='music_music_album_i_aadc41_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['language'], name='music_music_languag_9ae7de_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['-play_count'], name='music_music_play_co_64ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='music_favor_user_id_01b68e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'music')},
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', '-release_date'], name='music_album_artist__7a76e8_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['advertisement', '-created_at'], name='music_adimp_adverti_907f35_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', '-created_at'], name='music_adimp_user_id_6c4980_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['advertisement', '-created_at'], name='music_adcli_adverti_d19a44_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['user', '-created_at'], name='music_adcli_user_id_b329c2_idx'),
        ),
    ]
