# Generated by Django 4.2.28 on 2026-02-17 17:49

import django.core.validators
from django.db import migrations, models
import music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='cover image URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='image URL'),
        ),
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='audio URL'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'aac', 'm4a']), music.validators.validate_audio_file_size], verbose_name='audio file'),
        ),
    ]
