# Generated by Django 4.2.28 on 2026-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_cover_image_url_artist_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('ARABIC', 'Arabic'), ('MALAYALAM', 'Malayalam'), ('HINDI', 'Hindi'), ('TELUGU', 'Telugu'), ('KANNADA', 'Kannada'), ('TAMIL', 'Tamil'), ('INSTRUMENTAL', 'Instrumental'), ('BILINGUAL', 'Bilingual')], default='ENGLISH', max_length=20, verbose_name='language'),
        ),
    ]
