# Generated by Django 4.2.28 on 2026-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_language'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='album',
            name='music_album_artist__7a76e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='music',
            name='music_music_artist__f29e89_idx',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-release_date'], name='music_album_release_31abd8_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['-created_at'], name='music_music_created_c59461_idx'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.artist', verbose_name='artists'),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='music_tracks', to='music.artist', verbose_name='artists'),
        ),
    ]
