# Generated by Django 4.2.28 on 2026-02-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='thumb_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='thumbnail URL'),
        ),
    ]
