from typing import Any

from pydantic import BaseModel, Field


class CategoryItem(BaseModel):
    id: str = Field(..., description="Unique slug ID of category")
    name: str = Field(..., description="Display title of the category")
    title: str = Field(..., description="Display title (same as name)")
    type: str = Field(..., description="Category group: 'mood', 'activity', or 'genre'")
    emoji: str | None = Field(default=None, description="Emoji representation")
    image_url: str | None = Field(default=None, description="Artwork or icon image URL")
    gradient: list[str] = Field(default_factory=list, description="Primary & secondary HEX color codes for card backgrounds")
    query: str = Field(..., description="YouTube Music search query used to load songs and playlists")
    description: str | None = Field(default=None, description="Short descriptive tagline")


class MoodAndGenresData(BaseModel):
    moods: list[CategoryItem] = Field(default_factory=list, description="Mood categories")
    activities: list[CategoryItem] = Field(default_factory=list, description="Activity categories")
    genres: list[CategoryItem] = Field(default_factory=list, description="Genre categories")


# Curated catalog of Moods, Activities, and Genres with high-vibrancy gradients and targeted music queries
MOOD_CATEGORIES: list[dict[str, Any]] = [
    {
        "id": "chill",
        "name": "Chill",
        "title": "Chill",
        "type": "mood",
        "emoji": "🍃",
        "image_url": "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#11998e", "#38ef7d"],
        "query": "malayalam chill acoustic songs",
        "description": "Slow, relaxing and chill melodies to unwind",
    },
    {
        "id": "love",
        "name": "Love",
        "title": "Love",
        "type": "mood",
        "emoji": "❤️",
        "image_url": "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#ff758c", "#ff7eb3"],
        "query": "malayalam romantic love hits",
        "description": "Soul-stirring romantic love songs",
    },
    {
        "id": "sad",
        "name": "Sad",
        "title": "Sad",
        "type": "mood",
        "emoji": "🌧️",
        "image_url": "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#4b6cb7", "#182848"],
        "query": "malayalam sad emotional heart touch songs",
        "description": "Deep, emotional and reflective songs",
    },
    {
        "id": "happy",
        "name": "Happy",
        "title": "Happy",
        "type": "mood",
        "emoji": "☀️",
        "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#f7971e", "#ffd200"],
        "query": "malayalam feel good happy celebration songs",
        "description": "Uplifting and cheerful vibes to brighten your day",
    },
    {
        "id": "relax",
        "name": "Relax",
        "title": "Relax",
        "type": "mood",
        "emoji": "🌊",
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#00c6ff", "#0072ff"],
        "query": "malayalam relaxing peaceful melodies",
        "description": "Soothing tunes to de-stress and calm the mind",
    },
    {
        "id": "party",
        "name": "Party",
        "title": "Party",
        "type": "mood",
        "emoji": "🎉",
        "image_url": "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#f857a6", "#ff5858"],
        "query": "malayalam dance party dj hits",
        "description": "Energetic bass-heavy party bangers",
    },
    {
        "id": "romantic",
        "name": "Romantic",
        "title": "Romantic",
        "type": "mood",
        "emoji": "💖",
        "image_url": "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#ee9ca7", "#ffdde1"],
        "query": "malayalam romantic melodies",
        "description": "Sweet melodies dedicated to special moments",
    },
    {
        "id": "motivation",
        "name": "Motivation",
        "title": "Motivation",
        "type": "mood",
        "emoji": "⚡",
        "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#f12711", "#f5af19"],
        "query": "malayalam motivational workout high energy songs",
        "description": "Powerful anthems to push your limits",
    },
    {
        "id": "nostalgic",
        "name": "Nostalgic",
        "title": "Nostalgic",
        "type": "mood",
        "emoji": "📻",
        "image_url": "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#654ea3", "#eaafc8"],
        "query": "malayalam nostalgia 90s 2000s super hit songs",
        "description": "Treasured memories and beloved 90s/2000s gems",
    },
    {
        "id": "peaceful",
        "name": "Peaceful",
        "title": "Peaceful",
        "type": "mood",
        "emoji": "🕊️",
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#134e5e", "#71b280"],
        "query": "malayalam peaceful calm melodies",
        "description": "Serene acoustic sounds for tranquil moments",
    },
]

ACTIVITY_CATEGORIES: list[dict[str, Any]] = [
    {
        "id": "gym-workout",
        "name": "Gym / Workout",
        "title": "Gym / Workout",
        "type": "activity",
        "emoji": "💪",
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#eb3349", "#f45c43"],
        "query": "malayalam gym workout high energy songs",
        "description": "Energetic and motivational workout songs",
    },
    {
        "id": "driving",
        "name": "Driving",
        "title": "Driving",
        "type": "activity",
        "emoji": "🚗",
        "image_url": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#24c6dc", "#514a9d"],
        "query": "malayalam driving songs road trip playlist",
        "description": "Enjoyable songs suitable for driving and road trips",
    },
    {
        "id": "road-trip",
        "name": "Road Trip",
        "title": "Road Trip",
        "type": "activity",
        "emoji": "🛣️",
        "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#ff512f", "#dd2476"],
        "query": "malayalam travel road trip songs",
        "description": "The ultimate soundtrack for scenic road trips",
    },
    {
        "id": "work-focus",
        "name": "Work / Focus",
        "title": "Work / Focus",
        "type": "activity",
        "emoji": "💻",
        "image_url": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#1f4037", "#99f2c8"],
        "query": "calm instrumental focus concentration music",
        "description": "Instrumental and low-distraction music",
    },
    {
        "id": "study",
        "name": "Study",
        "title": "Study",
        "type": "activity",
        "emoji": "📚",
        "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#3a7bd5", "#3a6073"],
        "query": "chill lofi instrumental study music",
        "description": "Calm and focus-oriented music",
    },
    {
        "id": "running",
        "name": "Running",
        "title": "Running",
        "type": "activity",
        "emoji": "🏃",
        "image_url": "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#fa709a", "#fee140"],
        "query": "high bpm running workout songs",
        "description": "Fast-paced rhythms to match your stride",
    },
    {
        "id": "sleep",
        "name": "Sleep",
        "title": "Sleep",
        "type": "activity",
        "emoji": "😴",
        "image_url": "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#0f2027", "#203a43"],
        "query": "malayalam lullaby calm deep sleep melodies",
        "description": "Slow and relaxing sleep melodies",
    },
    {
        "id": "morning",
        "name": "Morning",
        "title": "Morning",
        "type": "activity",
        "emoji": "🌅",
        "image_url": "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#ff9966", "#ff5e62"],
        "query": "malayalam positive morning vibes fresh songs",
        "description": "Refreshing and positive songs to begin the day",
    },
    {
        "id": "night",
        "name": "Night",
        "title": "Night",
        "type": "activity",
        "emoji": "🌙",
        "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#2c3e50", "#3498db"],
        "query": "malayalam late night chill melodies",
        "description": "Calm and mellow songs for late hours",
    },
    {
        "id": "coffee-time",
        "name": "Coffee Time",
        "title": "Coffee Time",
        "type": "activity",
        "emoji": "☕",
        "image_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#d38312", "#a83279"],
        "query": "acoustic coffee cafe relaxing songs",
        "description": "Warm acoustic cafe melodies with your cup of coffee",
    },
    {
        "id": "gaming",
        "name": "Gaming",
        "title": "Gaming",
        "type": "activity",
        "emoji": "🎮",
        "image_url": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#8a2387", "#e94057"],
        "query": "electronic gaming hype energetic songs",
        "description": "Immersive electronic beats for gaming sessions",
    },
    {
        "id": "meditation",
        "name": "Meditation",
        "title": "Meditation",
        "type": "activity",
        "emoji": "🧘",
        "image_url": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#00b09b", "#96c93e"],
        "query": "meditation flute ambient peaceful instrumental",
        "description": "Deep meditation and mindfulness ambiance",
    },
    {
        "id": "celebration",
        "name": "Celebration",
        "title": "Celebration",
        "type": "activity",
        "emoji": "🎉",
        "image_url": "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#ff0844", "#ffb199"],
        "query": "malayalam festive celebration dance hits",
        "description": "Festive songs for celebrations and gatherings",
    },
]

GENRE_CATEGORIES: list[dict[str, Any]] = [
    {
        "id": "melody",
        "name": "Melody",
        "title": "Melody",
        "type": "genre",
        "emoji": "🎵",
        "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#a18cd1", "#fbc2eb"],
        "query": "malayalam evergreen melodies",
        "description": "Sweet, soothing Malayalam melodies",
    },
    {
        "id": "malayalam-rap",
        "name": "Malayalam Rap",
        "title": "Malayalam Rap",
        "type": "genre",
        "emoji": "🎤",
        "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#434343", "#000000"],
        "query": "malayalam hip hop rap songs",
        "description": "Hard-hitting Malayalam rap and hip-hop",
    },
    {
        "id": "indie",
        "name": "Indie",
        "title": "Indie",
        "type": "genre",
        "emoji": "🎸",
        "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#ff8008", "#ffc837"],
        "query": "malayalam indie songs independent music",
        "description": "Original independent artists and unique sounds",
    },
    {
        "id": "classical",
        "name": "Classical",
        "title": "Classical",
        "type": "genre",
        "emoji": "🎻",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#e65c00", "#f9d423"],
        "query": "malayalam carnatic classical fusion songs",
        "description": "Carnatic ragas and classical fusion masterworks",
    },
    {
        "id": "instrumental",
        "name": "Instrumental",
        "title": "Instrumental",
        "type": "genre",
        "emoji": "🎹",
        "image_url": "https://images.unsplash.com/photo-1520523839898-507122133c43?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#2b5876", "#4e4376"],
        "query": "malayalam instrumental violin flute songs",
        "description": "Flute, violin, piano and acoustic instrumentals",
    },
    {
        "id": "devotional",
        "name": "Devotional",
        "title": "Devotional",
        "type": "genre",
        "emoji": "🪔",
        "image_url": "https://images.unsplash.com/photo-1609137144822-4458f2eb8538?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#f85032", "#e73827"],
        "query": "malayalam devotional songs",
        "description": "Sacred and divine spiritual songs",
    },
    {
        "id": "folk",
        "name": "Folk",
        "title": "Folk",
        "type": "genre",
        "emoji": "🪘",
        "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#bb672e", "#8b4513"],
        "query": "malayalam nadan pattukal folk songs",
        "description": "Traditional Nadan Pattukal and Kerala folk heritage",
    },
    {
        "id": "electronic",
        "name": "Electronic",
        "title": "Electronic",
        "type": "genre",
        "emoji": "⚡",
        "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#00f2fe", "#4facfe"],
        "query": "malayalam edm electronic dance remixes",
        "description": "Synth-driven EDM, club tracks and electronic grooves",
    },
    {
        "id": "rock",
        "name": "Rock",
        "title": "Rock",
        "type": "genre",
        "emoji": "🎸",
        "image_url": "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#373b44", "#4286f4"],
        "query": "malayalam rock band songs",
        "description": "High-voltage riffs and Kerala indie rock bands",
    },
    {
        "id": "acoustic",
        "name": "Acoustic",
        "title": "Acoustic",
        "type": "genre",
        "emoji": "🎼",
        "image_url": "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#56ab2f", "#a8e063"],
        "query": "malayalam acoustic guitar unplugged songs",
        "description": "Stripped-back unplugged melodies and guitar jams",
    },
    {
        "id": "old-songs",
        "name": "Old Songs",
        "title": "Old Songs",
        "type": "genre",
        "emoji": "📼",
        "image_url": "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?w=500&auto=format&fit=crop&q=80",
        "gradient": ["#834d9b", "#d047b8"],
        "query": "classic old malayalam evergreen hits",
        "description": "Evergreen golden classics from legendary eras",
    },
]

# Lookup dictionary by ID for O(1) retrieval
CATEGORIES_BY_ID: dict[str, dict[str, Any]] = {
    c["id"]: c for c in (MOOD_CATEGORIES + ACTIVITY_CATEGORIES + GENRE_CATEGORIES)
}


def get_all_categories_data() -> MoodAndGenresData:
    return MoodAndGenresData(
        moods=[CategoryItem(**c) for c in MOOD_CATEGORIES],
        activities=[CategoryItem(**c) for c in ACTIVITY_CATEGORIES],
        genres=[CategoryItem(**c) for c in GENRE_CATEGORIES],
    )


def find_category_by_id(category_id: str) -> CategoryItem | None:
    raw = CATEGORIES_BY_ID.get(category_id.strip().lower())
    if raw:
        return CategoryItem(**raw)
    return None
